<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html><html <?php language_attributes(); ?>><head>
<meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?php esc_html_e('My account', 'kklidi-members'); ?></title><?php wp_head(); ?>
</head><body <?php body_class('kklidi-members-page kklidi-members-page--account'); ?>><?php wp_body_open(); ?>
<main class="kklidi-members-main"><section class="kklidi-members-card" aria-labelledby="kklidi-members-page-title"><header class="kklidi-members-header"><h1 id="kklidi-members-page-title"><?php esc_html_e('My account', 'kklidi-members'); ?></h1><p><?php esc_html_e('Manage the account details owned by KKLIDI Members.', 'kklidi-members'); ?></p></header>
<?php if ($notice !== '') : ?><p class="kklidi-members-notice" role="status"><?php echo esc_html($notice); ?></p><?php endif; ?>
<?php if (!$user->exists()) : ?><p class="kklidi-members-hint"><?php esc_html_e('Log in to manage your profile, password, and consent settings.', 'kklidi-members'); ?></p><div class="kklidi-members-actions"><a class="kklidi-members-button" href="<?php echo esc_url($urls['login']); ?>"><?php esc_html_e('Log in', 'kklidi-members'); ?></a><a class="kklidi-members-button kklidi-members-button--secondary" href="<?php echo esc_url($urls['register']); ?>"><?php esc_html_e('Register', 'kklidi-members'); ?></a></div>
<?php else : ?><p class="kklidi-members-hint"><?php echo esc_html(sprintf(__('Hello, %s', 'kklidi-members'), $user->display_name)); ?></p><?php $route_links = array(array('url' => $urls['profile'], 'label' => __('Profile', 'kklidi-members')), array('url' => $urls['password'], 'label' => __('Change password', 'kklidi-members')), array('url' => $urls['consent'], 'label' => __('Consent settings', 'kklidi-members')), array('url' => $urls['withdrawal'], 'label' => __('Request withdrawal', 'kklidi-members')), array('url' => home_url('/'), 'label' => __('Home', 'kklidi-members'))); require KKLIDI_MEMBERS_DIR . 'templates/partials/route-links.php'; ?><?php if ($integration_links !== array()) : ?><section class="kklidi-members-section"><h2><?php esc_html_e('Connected services', 'kklidi-members'); ?></h2><p class="kklidi-members-hint"><?php esc_html_e('Open account areas provided by the connected service.', 'kklidi-members'); ?></p><nav aria-label="<?php esc_attr_e('Connected service navigation', 'kklidi-members'); ?>"><ul class="kklidi-members-nav"><?php foreach ($integration_links as $link) : ?><li><a href="<?php echo esc_url($link['url']); ?>"><?php echo esc_html($link['label']); ?></a></li><?php endforeach; ?></ul></nav></section><?php endif; ?><form class="kklidi-members-section" method="post" action="<?php echo esc_url($urls['logout']); ?>"><input type="hidden" name="kklidi_members_logout" value="1"><input type="hidden" name="redirect_to" value="<?php echo esc_attr(home_url('/')); ?>"><?php wp_nonce_field('kklidi_members_logout', '_kklidi_members_logout_nonce'); ?><button class="kklidi-members-button kklidi-members-button--secondary" type="submit"><?php esc_html_e('Log out', 'kklidi-members'); ?></button></form><?php endif; ?>
</section></main><?php wp_footer(); ?></body></html>
