<?php if (!defined('ABSPATH')) { exit; } ?>
<div class="wrap kklidi-members-admin"><h1><?php esc_html_e('KKLIDI Members', 'kklidi-members'); ?></h1>
<?php if (isset($_GET['updated'])) : ?><div class="notice notice-success is-dismissible" role="status"><p><?php esc_html_e('Settings saved.', 'kklidi-members'); ?></p></div><?php endif; ?>
<section class="kklidi-members-admin-card"><h2><?php esc_html_e('Member settings', 'kklidi-members'); ?></h2><p><?php esc_html_e('Public registration is enabled only when WordPress registration is allowed and the required documents are published.', 'kklidi-members'); ?></p>
<form method="post"><?php wp_nonce_field('kklidi_members_admin', '_kklidi_members_admin_nonce'); ?><input type="hidden" name="kklidi_members_admin_action" value="save_settings">
<p><label><input type="checkbox" name="own_login_url" value="1" <?php checked(get_option('kklidi_members_own_login_url'), '1'); ?>> <?php esc_html_e('Members owns the Core login URL', 'kklidi-members'); ?></label></p><p><label><input type="checkbox" name="own_register_url" value="1" <?php checked(get_option('kklidi_members_own_register_url'), '1'); ?>> <?php esc_html_e('Members owns the Core registration URL', 'kklidi-members'); ?></label></p>
<?php foreach (array('service' => __('Service terms', 'kklidi-members'), 'privacy' => __('Privacy policy', 'kklidi-members'), 'marketing' => __('Optional marketing consent', 'kklidi-members')) as $type => $label) : $document = $documents[$type]; ?><h3><?php echo esc_html($label); ?></h3><p><label><?php esc_html_e('New version', 'kklidi-members'); ?> <input name="<?php echo esc_attr($type); ?>_version" value=""></label></p><p><label><?php esc_html_e('New document content', 'kklidi-members'); ?><br><textarea class="large-text" rows="5" name="<?php echo esc_attr($type); ?>_content"></textarea></label></p><?php if ($document !== array()) : ?><p><?php esc_html_e('Current version:', 'kklidi-members'); ?> <?php echo esc_html($document['version']); ?> / SHA-256 <?php echo esc_html($document['hash']); ?></p><?php endif; ?><?php endforeach; ?><p><button class="button button-primary" type="submit"><?php esc_html_e('Save settings', 'kklidi-members'); ?></button></p></form>
</section>
<section class="kklidi-members-admin-card"><h2><?php esc_html_e('Pending withdrawals', 'kklidi-members'); ?></h2><table class="widefat striped kklidi-members-admin-table"><thead><tr><th scope="col"><?php esc_html_e('User ID', 'kklidi-members'); ?></th><th scope="col"><?php esc_html_e('Display name', 'kklidi-members'); ?></th><th scope="col"><?php esc_html_e('Action', 'kklidi-members'); ?></th></tr></thead><tbody><?php foreach ($queue as $queued_user) : ?><tr><td><?php echo (int) $queued_user->ID; ?></td><td><?php echo esc_html($queued_user->display_name); ?></td><td><form method="post"><?php wp_nonce_field('kklidi_members_admin', '_kklidi_members_admin_nonce'); ?><input type="hidden" name="kklidi_members_admin_action" value="finalize_withdrawal"><input type="hidden" name="user_id" value="<?php echo (int) $queued_user->ID; ?>"><button class="button" type="submit"><?php esc_html_e('Confirm login block', 'kklidi-members'); ?></button></form></td></tr><?php endforeach; ?><?php if (!$queue) : ?><tr><td colspan="3"><?php esc_html_e('No pending requests.', 'kklidi-members'); ?></td></tr><?php endif; ?></tbody></table></section>
<section class="kklidi-members-admin-card"><h2><?php esc_html_e('Recent security events', 'kklidi-members'); ?></h2><table class="widefat striped kklidi-members-admin-table"><thead><tr><th scope="col">ID</th><th scope="col"><?php esc_html_e('User ID', 'kklidi-members'); ?></th><th scope="col">UTC</th><th scope="col"><?php esc_html_e('Type', 'kklidi-members'); ?></th><th scope="col"><?php esc_html_e('Result', 'kklidi-members'); ?></th><th scope="col"><?php esc_html_e('Reason', 'kklidi-members'); ?></th></tr></thead><tbody><?php foreach ($audit_rows as $row) : ?><tr><td><?php echo (int) $row->id; ?></td><td><?php echo $row->user_id ? (int) $row->user_id : '—'; ?></td><td><?php echo esc_html($row->occurred_at_utc); ?></td><td><?php echo esc_html($row->event_type); ?></td><td><?php echo esc_html($row->result); ?></td><td><?php echo esc_html($row->reason_code); ?></td></tr><?php endforeach; ?></tbody></table></section>
</div>
