<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html><html <?php language_attributes(); ?>><head>
<meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?php esc_html_e('Consent settings', 'kklidi-members'); ?></title><?php wp_head(); ?>
</head><body <?php body_class('kklidi-members-page kklidi-members-page--consent'); ?>><?php wp_body_open(); ?>
<main class="kklidi-members-main"><section class="kklidi-members-card" aria-labelledby="kklidi-members-page-title"><header class="kklidi-members-header"><h1 id="kklidi-members-page-title"><?php esc_html_e('Consent settings', 'kklidi-members'); ?></h1></header>
<?php if ($message !== '') : ?><p class="kklidi-members-notice" role="status"><?php echo esc_html($message); ?></p><?php endif; ?>
<form class="kklidi-members-form" method="post"><input type="hidden" name="kklidi_members_consent" value="1"><input type="hidden" name="request_id" value="<?php echo esc_attr($request_id); ?>"><?php wp_nonce_field('kklidi_members_consent', '_kklidi_members_consent_nonce'); ?>
<?php foreach (array('service' => __('Service terms', 'kklidi-members'), 'privacy' => __('Privacy policy', 'kklidi-members')) as $type => $label) : ?><section class="kklidi-members-section"><h2><?php echo esc_html($label); ?></h2><?php if ($documents[$type] !== array()) : ?><div class="kklidi-members-document"><?php echo wp_kses_post($documents[$type]['content']); ?></div><label class="kklidi-members-check"><input type="checkbox" name="consent_<?php echo esc_attr($type); ?>" value="1" <?php checked($current[$type]); ?> required> <?php esc_html_e('I agree to the current version.', 'kklidi-members'); ?></label><?php else : ?><p class="kklidi-members-hint"><?php esc_html_e('An administrator must publish this document first.', 'kklidi-members'); ?></p><?php endif; ?></section><?php endforeach; ?>
<?php if ($documents['marketing'] !== array()) : ?><section class="kklidi-members-section"><h2><?php esc_html_e('Marketing communications', 'kklidi-members'); ?></h2><div class="kklidi-members-document"><?php echo wp_kses_post($documents['marketing']['content']); ?></div><label class="kklidi-members-check"><input type="checkbox" name="consent_marketing" value="1" <?php checked($current['marketing']); ?>> <?php esc_html_e('Optional consent', 'kklidi-members'); ?></label></section><?php endif; ?>
<button class="kklidi-members-button" type="submit"><?php esc_html_e('Save consent settings', 'kklidi-members'); ?></button></form>
</section></main><?php wp_footer(); ?></body></html>
