<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html><html <?php language_attributes(); ?>><head>
<meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?php esc_html_e('Consent settings', 'kklidi-members'); ?></title><?php wp_head(); ?>
</head><body <?php body_class('kklidi-members-page kklidi-members-page--consent'); ?>><?php wp_body_open(); ?>
<main class="kklidi-members-main"><section class="kklidi-members-card" aria-labelledby="kklidi-members-page-title"><header class="kklidi-members-header"><h1 id="kklidi-members-page-title"><?php esc_html_e('Consent settings', 'kklidi-members'); ?></h1><p><?php esc_html_e('Review the current document versions and manage your consent.', 'kklidi-members'); ?></p></header>
<?php if ($message !== '') : ?><p class="kklidi-members-notice<?php echo $message_type === 'error' ? ' kklidi-members-notice--error' : ''; ?>" role="<?php echo $message_type === 'error' ? 'alert' : 'status'; ?>"><?php echo esc_html($message); ?></p><?php endif; ?>
<?php if ($field_errors !== array()) : ?><div class="kklidi-members-field-errors" role="alert"><p><?php esc_html_e('Please correct the highlighted fields.', 'kklidi-members'); ?></p><ul><?php foreach ($field_errors as $type => $error) : ?><li><a href="#kklidi-members-consent-<?php echo esc_attr($type); ?>"><?php echo esc_html($error); ?></a></li><?php endforeach; ?></ul></div><?php endif; ?>
<form class="kklidi-members-form" method="post"><input type="hidden" name="kklidi_members_consent" value="1"><input type="hidden" name="request_id" value="<?php echo esc_attr($request_id); ?>"><?php wp_nonce_field('kklidi_members_consent', '_kklidi_members_consent_nonce'); ?>
<?php foreach (array('service' => __('Service terms', 'kklidi-members'), 'privacy' => __('Privacy policy', 'kklidi-members')) as $type => $label) : ?><section class="kklidi-members-section" id="kklidi-members-consent-<?php echo esc_attr($type); ?>"><h2><?php echo esc_html($label); ?></h2><?php if ($documents[$type] !== array()) : ?><p class="kklidi-members-hint"><?php echo esc_html(sprintf(__('Current version: %s', 'kklidi-members'), $documents[$type]['version'])); ?> · <a href="#kklidi-members-consent-<?php echo esc_attr($type); ?>-document"><?php esc_html_e('Read the full document', 'kklidi-members'); ?></a></p><details id="kklidi-members-consent-<?php echo esc_attr($type); ?>-document"><summary><?php esc_html_e('Show document', 'kklidi-members'); ?></summary><div class="kklidi-members-document"><?php echo wp_kses_post($documents[$type]['content']); ?></div></details><label class="kklidi-members-check" for="kklidi-members-consent-<?php echo esc_attr($type); ?>-input"><input id="kklidi-members-consent-<?php echo esc_attr($type); ?>-input" type="checkbox" name="consent_<?php echo esc_attr($type); ?>" value="1" <?php checked($current[$type]); ?> required<?php echo isset($field_errors[$type]) ? ' aria-invalid="true" aria-describedby="kklidi-members-consent-' . esc_attr($type) . '-error"' : ''; ?>> <?php esc_html_e('I agree to the current version.', 'kklidi-members'); ?></label><?php if (isset($field_errors[$type])) : ?><span class="kklidi-members-field-error" id="kklidi-members-consent-<?php echo esc_attr($type); ?>-error"><?php echo esc_html($field_errors[$type]); ?></span><?php endif; ?><?php else : ?><p class="kklidi-members-hint"><?php esc_html_e('An administrator must publish this document first.', 'kklidi-members'); ?></p><?php endif; ?></section><?php endforeach; ?>
<?php if ($documents['marketing'] !== array()) : ?><section class="kklidi-members-section"><h2><?php esc_html_e('Marketing communications', 'kklidi-members'); ?></h2><p class="kklidi-members-hint"><?php echo esc_html(sprintf(__('Current version: %s', 'kklidi-members'), $documents['marketing']['version'])); ?></p><details><summary><?php esc_html_e('Show document', 'kklidi-members'); ?></summary><div class="kklidi-members-document"><?php echo wp_kses_post($documents['marketing']['content']); ?></div></details><label class="kklidi-members-check" for="kklidi-members-consent-marketing-input"><input id="kklidi-members-consent-marketing-input" type="checkbox" name="consent_marketing" value="1" <?php checked($current['marketing']); ?>> <?php esc_html_e('Optional consent', 'kklidi-members'); ?></label></section><?php endif; ?>
<button class="kklidi-members-button" type="submit"><?php esc_html_e('Save consent settings', 'kklidi-members'); ?></button></form>
<?php $route_links = array(array('url' => $account_url, 'label' => __('Account', 'kklidi-members')), array('url' => kklidi_members_profile_url(), 'label' => __('Profile', 'kklidi-members')), array('url' => home_url('/'), 'label' => __('Home', 'kklidi-members'))); require KKLIDI_MEMBERS_DIR . 'templates/partials/route-links.php'; ?>
</section></main><?php wp_footer(); ?></body></html>
