<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html><html <?php language_attributes(); ?>><head>
<meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?php esc_html_e('Change password', 'kklidi-members'); ?></title><?php wp_head(); ?>
</head><body <?php body_class('kklidi-members-page kklidi-members-page--password'); ?>><?php wp_body_open(); ?>
<main class="kklidi-members-main"><section class="kklidi-members-card" aria-labelledby="kklidi-members-page-title"><header class="kklidi-members-header"><p class="kklidi-members-eyebrow"><a class="kklidi-members-brand" href="<?php echo esc_url(home_url('/')); ?>"><?php echo esc_html(get_bloginfo('name')); ?></a></p><h1 id="kklidi-members-page-title"><?php esc_html_e('Change password', 'kklidi-members'); ?></h1><p><?php esc_html_e('Confirm your current password before choosing a new one.', 'kklidi-members'); ?></p></header>
<?php if ($message !== '') : ?><p class="kklidi-members-notice kklidi-members-notice--error" role="alert"><?php echo esc_html($message); ?></p><?php endif; ?>
<?php if ($field_errors !== array()) : ?><div class="kklidi-members-field-errors" role="alert"><p><?php esc_html_e('Please correct the highlighted fields.', 'kklidi-members'); ?></p><ul><?php foreach ($field_errors as $field => $error) : ?><li><a href="#kklidi-members-password-<?php echo esc_attr($field); ?>"><?php echo esc_html($error); ?></a></li><?php endforeach; ?></ul></div><?php endif; ?>
<form class="kklidi-members-form" method="post"><input type="hidden" name="kklidi_members_password" value="1"><?php wp_nonce_field('kklidi_members_password', '_kklidi_members_password_nonce'); ?>
<?php foreach (array('current_password' => array(__('Current password', 'kklidi-members'), 'current-password'), 'new_password' => array(__('New password', 'kklidi-members'), 'new-password'), 'new_password_confirm' => array(__('Confirm new password', 'kklidi-members'), 'new-password')) as $field => $settings) : ?><div class="kklidi-members-field"><label for="kklidi-members-password-<?php echo esc_attr($field); ?>"><?php echo esc_html($settings[0]); ?></label><div class="kklidi-members-password-control"><input id="kklidi-members-password-<?php echo esc_attr($field); ?>" type="password" name="<?php echo esc_attr($field); ?>" autocomplete="<?php echo esc_attr($settings[1]); ?>"<?php echo $field === 'current_password' ? '' : ' minlength="12"'; ?> required data-kklidi-members-password<?php echo isset($field_errors[$field]) ? ' aria-invalid="true" aria-describedby="kklidi-members-password-' . esc_attr($field) . '-error"' : ''; ?>><button class="kklidi-members-password-toggle" type="button" data-kklidi-members-password-toggle aria-controls="kklidi-members-password-<?php echo esc_attr($field); ?>" aria-pressed="false" aria-label="<?php esc_attr_e('Show password', 'kklidi-members'); ?>" data-show-label="<?php esc_attr_e('Show password', 'kklidi-members'); ?>" data-hide-label="<?php esc_attr_e('Hide password', 'kklidi-members'); ?>"><svg class="kklidi-members-icon--on" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M2.2 12s3.5-6 9.8-6 9.8 6 9.8 6-3.5 6-9.8 6-9.8-6-9.8-6Zm9.8 3.2a3.2 3.2 0 1 0 0-6.4 3.2 3.2 0 0 0 0 6.4Z" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linejoin="round"/></svg><svg class="kklidi-members-icon--off" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="m3 3 18 18M10.6 6.2A10.8 10.8 0 0 1 12 6c6.3 0 9.8 6 9.8 6a17 17 0 0 1-3.1 3.7M6.3 6.8C3.7 8.6 2.2 12 2.2 12s3.5 6 9.8 6a9.7 9.7 0 0 0 3-.5M9.9 9.9a3 3 0 0 0 4.2 4.2" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div><?php if (isset($field_errors[$field])) : ?><span class="kklidi-members-field-error" id="kklidi-members-password-<?php echo esc_attr($field); ?>-error"><?php echo esc_html($field_errors[$field]); ?></span><?php endif; ?></div><?php endforeach; ?>
<button class="kklidi-members-button" type="submit"><?php esc_html_e('Change password', 'kklidi-members'); ?></button></form>
<nav class="kklidi-members-form-links kklidi-members-form-links--primary" aria-label="<?php esc_attr_e('Password navigation', 'kklidi-members'); ?>"><a href="<?php echo esc_url(kklidi_members_password_reset_url()); ?>"><?php esc_html_e('Forgot your password?', 'kklidi-members'); ?></a></nav><nav class="kklidi-members-form-links kklidi-members-form-links--secondary" aria-label="<?php esc_attr_e('Account links', 'kklidi-members'); ?>"><a href="<?php echo esc_url($account_url); ?>"><?php esc_html_e('Back to account', 'kklidi-members'); ?></a></nav>
</section></main><?php wp_footer(); ?></body></html>
