<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html><html <?php language_attributes(); ?>><head>
<meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?php esc_html_e('Change password', 'kklidi-members'); ?></title><?php wp_head(); ?>
</head><body <?php body_class('kklidi-members-page kklidi-members-page--password'); ?>><?php wp_body_open(); ?>
<main class="kklidi-members-main"><section class="kklidi-members-card" aria-labelledby="kklidi-members-page-title"><header class="kklidi-members-header"><p class="kklidi-members-eyebrow"><?php echo esc_html(get_bloginfo('name')); ?></p><h1 id="kklidi-members-page-title"><?php esc_html_e('Change password', 'kklidi-members'); ?></h1><p><?php esc_html_e('Confirm your current password before choosing a new one.', 'kklidi-members'); ?></p></header>
<?php if ($message !== '') : ?><p class="kklidi-members-notice kklidi-members-notice--error" role="alert"><?php echo esc_html($message); ?></p><?php endif; ?>
<?php if ($field_errors !== array()) : ?><div class="kklidi-members-field-errors" role="alert"><p><?php esc_html_e('Please correct the highlighted fields.', 'kklidi-members'); ?></p><ul><?php foreach ($field_errors as $field => $error) : ?><li><a href="#kklidi-members-password-<?php echo esc_attr($field); ?>"><?php echo esc_html($error); ?></a></li><?php endforeach; ?></ul></div><?php endif; ?>
<form class="kklidi-members-form" method="post"><input type="hidden" name="kklidi_members_password" value="1"><?php wp_nonce_field('kklidi_members_password', '_kklidi_members_password_nonce'); ?>
<?php foreach (array('current_password' => array(__('Current password', 'kklidi-members'), 'current-password'), 'new_password' => array(__('New password', 'kklidi-members'), 'new-password'), 'new_password_confirm' => array(__('Confirm new password', 'kklidi-members'), 'new-password')) as $field => $settings) : ?><div class="kklidi-members-field"><label for="kklidi-members-password-<?php echo esc_attr($field); ?>"><?php echo esc_html($settings[0]); ?></label><div class="kklidi-members-password-control"><input id="kklidi-members-password-<?php echo esc_attr($field); ?>" type="password" name="<?php echo esc_attr($field); ?>" autocomplete="<?php echo esc_attr($settings[1]); ?>"<?php echo $field === 'current_password' ? '' : ' minlength="12"'; ?> required data-kklidi-members-password<?php echo isset($field_errors[$field]) ? ' aria-invalid="true" aria-describedby="kklidi-members-password-' . esc_attr($field) . '-error"' : ''; ?>><button class="kklidi-members-password-toggle" type="button" data-kklidi-members-password-toggle aria-controls="kklidi-members-password-<?php echo esc_attr($field); ?>" aria-pressed="false" data-show-label="<?php esc_attr_e('Show password', 'kklidi-members'); ?>" data-hide-label="<?php esc_attr_e('Hide password', 'kklidi-members'); ?>"><?php esc_html_e('Show password', 'kklidi-members'); ?></button></div><?php if (isset($field_errors[$field])) : ?><span class="kklidi-members-field-error" id="kklidi-members-password-<?php echo esc_attr($field); ?>-error"><?php echo esc_html($field_errors[$field]); ?></span><?php endif; ?></div><?php endforeach; ?>
<button class="kklidi-members-button" type="submit"><?php esc_html_e('Change password', 'kklidi-members'); ?></button></form>
<nav class="kklidi-members-form-links" aria-label="<?php esc_attr_e('Password navigation', 'kklidi-members'); ?>"><a href="<?php echo esc_url(kklidi_members_password_reset_url()); ?>"><?php esc_html_e('Forgot your password?', 'kklidi-members'); ?></a><a href="<?php echo esc_url($account_url); ?>"><?php esc_html_e('Back to account', 'kklidi-members'); ?></a></nav>
</section></main><?php wp_footer(); ?></body></html>
