<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html><html <?php language_attributes(); ?>><head>
<meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?php esc_html_e('Profile', 'kklidi-members'); ?></title><?php wp_head(); ?>
</head><body <?php body_class('kklidi-members-page kklidi-members-page--profile'); ?>><?php wp_body_open(); ?>
<main class="kklidi-members-main"><section class="kklidi-members-card" aria-labelledby="kklidi-members-page-title"><header class="kklidi-members-header"><h1 id="kklidi-members-page-title"><?php esc_html_e('Profile', 'kklidi-members'); ?></h1><p><?php esc_html_e('Update your account profile. Your login email is read-only.', 'kklidi-members'); ?></p></header>
<?php if ($message !== '') : ?><p class="kklidi-members-notice<?php echo $message_type === 'error' ? ' kklidi-members-notice--error' : ''; ?>" role="<?php echo $message_type === 'error' ? 'alert' : 'status'; ?>"><?php echo esc_html($message); ?></p><?php endif; ?>
<?php if ($field_errors !== array()) : ?><div class="kklidi-members-field-errors" role="alert"><p><?php esc_html_e('Please correct the highlighted fields.', 'kklidi-members'); ?></p><ul><?php foreach ($field_errors as $field => $error) : ?><li><a href="#kklidi-members-profile-<?php echo esc_attr($field); ?>"><?php echo esc_html($error); ?></a></li><?php endforeach; ?></ul></div><?php endif; ?>
<form class="kklidi-members-form" method="post"><input type="hidden" name="kklidi_members_profile" value="1"><?php wp_nonce_field('kklidi_members_profile', '_kklidi_members_profile_nonce'); ?>
<label class="kklidi-members-field" for="kklidi-members-profile-email"><?php esc_html_e('Email', 'kklidi-members'); ?><input id="kklidi-members-profile-email" type="email" value="<?php echo esc_attr($user->user_email); ?>" autocomplete="email" readonly></label>
<label class="kklidi-members-field" for="kklidi-members-profile-first-name"><?php esc_html_e('First name', 'kklidi-members'); ?><input id="kklidi-members-profile-first-name" name="first_name" autocomplete="given-name" value="<?php echo esc_attr($values['first_name']); ?>"></label>
<label class="kklidi-members-field" for="kklidi-members-profile-last-name"><?php esc_html_e('Last name', 'kklidi-members'); ?><input id="kklidi-members-profile-last-name" name="last_name" autocomplete="family-name" value="<?php echo esc_attr($values['last_name']); ?>"></label>
<label class="kklidi-members-field" for="kklidi-members-profile-display_name"><?php esc_html_e('Display name (nickname)', 'kklidi-members'); ?><input id="kklidi-members-profile-display_name" name="display_name" autocomplete="nickname" value="<?php echo esc_attr($values['display_name']); ?>" required aria-describedby="kklidi-members-profile-display-name-hint<?php echo isset($field_errors['display_name']) ? ' kklidi-members-profile-display-name-error' : ''; ?>"<?php echo isset($field_errors['display_name']) ? ' aria-invalid="true"' : ''; ?>><span class="kklidi-members-field-help" id="kklidi-members-profile-display-name-hint"><?php esc_html_e('This name is visible to other users. It is not used as a login ID.', 'kklidi-members'); ?></span><?php if (isset($field_errors['display_name'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-profile-display-name-error"><?php echo esc_html($field_errors['display_name']); ?></span><?php endif; ?></label>
<label class="kklidi-members-field" for="kklidi-members-profile-phone"><?php esc_html_e('Phone', 'kklidi-members'); ?><input id="kklidi-members-profile-phone" name="phone" autocomplete="tel" value="<?php echo esc_attr($values['phone']); ?>" inputmode="tel"<?php echo isset($field_errors['phone']) ? ' aria-invalid="true" aria-describedby="kklidi-members-profile-phone-error"' : ''; ?>><?php if (isset($field_errors['phone'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-profile-phone-error"><?php echo esc_html($field_errors['phone']); ?></span><?php endif; ?></label>
<label class="kklidi-members-field" for="kklidi-members-profile-description"><?php esc_html_e('Bio', 'kklidi-members'); ?><textarea id="kklidi-members-profile-description" name="description"><?php echo esc_textarea($values['description']); ?></textarea></label>
<button class="kklidi-members-button" type="submit"><?php esc_html_e('Save', 'kklidi-members'); ?></button></form>
<?php $route_links = array(array('url' => $account_url, 'label' => __('Account', 'kklidi-members')), array('url' => kklidi_members_password_url(), 'label' => __('Change password', 'kklidi-members')), array('url' => home_url('/'), 'label' => __('Home', 'kklidi-members'))); require KKLIDI_MEMBERS_DIR . 'templates/partials/route-links.php'; ?>
</section></main><?php wp_footer(); ?></body></html>
