<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html>
<html <?php language_attributes(); ?>><head>
<meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex,nofollow"><title><?php esc_html_e('Register', 'kklidi-members'); ?></title><?php wp_head(); ?>
</head><body <?php body_class('kklidi-members-page kklidi-members-page--register'); ?>><?php wp_body_open(); ?>
<main class="kklidi-members-main"><section class="kklidi-members-card" aria-labelledby="kklidi-members-page-title">
<header class="kklidi-members-header"><p class="kklidi-members-eyebrow"><?php echo esc_html(get_bloginfo('name')); ?></p><h1 id="kklidi-members-page-title"><?php esc_html_e('Register', 'kklidi-members'); ?></h1><p><?php esc_html_e('Create your account with WordPress Core authentication.', 'kklidi-members'); ?></p></header>
<?php if ($message !== '') : ?><p class="kklidi-members-notice kklidi-members-notice--error" role="alert"><?php echo esc_html($message); ?></p><?php endif; ?>
<?php if ($field_errors !== array()) : ?><div class="kklidi-members-field-errors" role="alert"><p><?php esc_html_e('Please correct the highlighted fields.', 'kklidi-members'); ?></p><ul><?php foreach ($field_errors as $field => $field_error) : ?><li><a href="#kklidi-members-<?php echo esc_attr($field); ?>"><?php echo esc_html($field_error); ?></a></li><?php endforeach; ?></ul></div><?php endif; ?>
<?php if ($enabled) : ?><form class="kklidi-members-form" method="post" data-kklidi-members-register><input type="hidden" name="kklidi_members_register" value="1"><input type="hidden" name="request_id" value="<?php echo esc_attr($request_id); ?>">
<?php wp_nonce_field('kklidi_members_register', '_kklidi_members_register_nonce'); ?><?php echo $guest_fields; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated escaped fields. ?>
<label class="kklidi-members-field" for="kklidi-members-email"><?php esc_html_e('Email', 'kklidi-members'); ?><input id="kklidi-members-email" type="email" name="email" autocomplete="email" value="<?php echo esc_attr($values['email']); ?>" required<?php echo isset($field_errors['email']) ? ' aria-invalid="true" aria-describedby="kklidi-members-email-error"' : ''; ?>><?php if (isset($field_errors['email'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-email-error"><?php echo esc_html($field_errors['email']); ?></span><?php endif; ?></label>
<div class="kklidi-members-field"><label for="kklidi-members-register-password"><?php esc_html_e('Password', 'kklidi-members'); ?></label><div class="kklidi-members-password-control"><input id="kklidi-members-register-password" type="password" name="password" autocomplete="new-password" minlength="12" required data-kklidi-members-password<?php echo isset($field_errors['password']) ? ' aria-invalid="true" aria-describedby="kklidi-members-register-password-error"' : ''; ?>><button class="kklidi-members-password-toggle" type="button" data-kklidi-members-password-toggle aria-controls="kklidi-members-register-password" aria-pressed="false" data-show-label="<?php esc_attr_e('Show password', 'kklidi-members'); ?>" data-hide-label="<?php esc_attr_e('Hide password', 'kklidi-members'); ?>"><?php esc_html_e('Show password', 'kklidi-members'); ?></button></div><?php if (isset($field_errors['password'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-register-password-error"><?php echo esc_html($field_errors['password']); ?></span><?php endif; ?></div>
<div class="kklidi-members-field"><label for="kklidi-members-register-password-confirm"><?php esc_html_e('Confirm password', 'kklidi-members'); ?></label><div class="kklidi-members-password-control"><input id="kklidi-members-register-password-confirm" type="password" name="password_confirm" autocomplete="new-password" minlength="12" required data-kklidi-members-password<?php echo isset($field_errors['password_confirm']) ? ' aria-invalid="true" aria-describedby="kklidi-members-register-password-confirm-error"' : ''; ?>><button class="kklidi-members-password-toggle" type="button" data-kklidi-members-password-toggle aria-controls="kklidi-members-register-password-confirm" aria-pressed="false" data-show-label="<?php esc_attr_e('Show password', 'kklidi-members'); ?>" data-hide-label="<?php esc_attr_e('Hide password', 'kklidi-members'); ?>"><?php esc_html_e('Show password', 'kklidi-members'); ?></button></div><?php if (isset($field_errors['password_confirm'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-register-password-confirm-error"><?php echo esc_html($field_errors['password_confirm']); ?></span><?php endif; ?></div>
<label class="kklidi-members-field" for="kklidi-members-first-name"><?php esc_html_e('First name', 'kklidi-members'); ?><input id="kklidi-members-first-name" name="first_name" autocomplete="given-name" value="<?php echo esc_attr($values['first_name']); ?>" required<?php echo isset($field_errors['first_name']) ? ' aria-invalid="true" aria-describedby="kklidi-members-first-name-error"' : ''; ?>><?php if (isset($field_errors['first_name'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-first-name-error"><?php echo esc_html($field_errors['first_name']); ?></span><?php endif; ?></label>
<label class="kklidi-members-field" for="kklidi-members-last-name"><?php esc_html_e('Last name', 'kklidi-members'); ?><input id="kklidi-members-last-name" name="last_name" autocomplete="family-name" value="<?php echo esc_attr($values['last_name']); ?>"></label>
<label class="kklidi-members-field" for="kklidi-members-display-name"><?php esc_html_e('Display name', 'kklidi-members'); ?><input id="kklidi-members-display-name" name="display_name" autocomplete="nickname" value="<?php echo esc_attr($values['display_name']); ?>" required<?php echo isset($field_errors['display_name']) ? ' aria-invalid="true" aria-describedby="kklidi-members-display-name-error"' : ''; ?>><?php if (isset($field_errors['display_name'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-display-name-error"><?php echo esc_html($field_errors['display_name']); ?></span><?php endif; ?></label>
<label class="kklidi-members-field" for="kklidi-members-phone"><?php esc_html_e('Phone', 'kklidi-members'); ?><input id="kklidi-members-phone" name="phone" autocomplete="tel" inputmode="tel" value="<?php echo esc_attr($values['phone']); ?>" aria-describedby="<?php echo isset($field_errors['phone']) ? 'kklidi-members-phone-error' : 'kklidi-members-phone-hint'; ?>"><?php if (isset($field_errors['phone'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-phone-error"><?php echo esc_html($field_errors['phone']); ?></span><?php else : ?><span class="kklidi-members-field-help" id="kklidi-members-phone-hint"><?php esc_html_e('Optional', 'kklidi-members'); ?></span><?php endif; ?></label>
<section class="kklidi-members-section"><h2><?php esc_html_e('Required consent', 'kklidi-members'); ?></h2><details open><summary><?php echo esc_html(sprintf(__('Service terms · Version %s', 'kklidi-members'), $service_document['version'])); ?></summary><div class="kklidi-members-document"><?php echo wp_kses_post($service_document['content']); ?></div></details><label class="kklidi-members-check" for="kklidi-members-consent-service"><input id="kklidi-members-consent-service" type="checkbox" name="consent_service" value="1" required<?php echo isset($field_errors['consent_service']) ? ' aria-invalid="true" aria-describedby="kklidi-members-consent-service-error"' : ''; ?>> <?php esc_html_e('I agree to the service terms.', 'kklidi-members'); ?></label><?php if (isset($field_errors['consent_service'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-consent-service-error"><?php echo esc_html($field_errors['consent_service']); ?></span><?php endif; ?><details open><summary><?php echo esc_html(sprintf(__('Privacy policy · Version %s', 'kklidi-members'), $privacy_document['version'])); ?></summary><div class="kklidi-members-document"><?php echo wp_kses_post($privacy_document['content']); ?></div></details><label class="kklidi-members-check" for="kklidi-members-consent-privacy"><input id="kklidi-members-consent-privacy" type="checkbox" name="consent_privacy" value="1" required<?php echo isset($field_errors['consent_privacy']) ? ' aria-invalid="true" aria-describedby="kklidi-members-consent-privacy-error"' : ''; ?>> <?php esc_html_e('I agree to the privacy policy.', 'kklidi-members'); ?></label><?php if (isset($field_errors['consent_privacy'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-consent-privacy-error"><?php echo esc_html($field_errors['consent_privacy']); ?></span><?php endif; ?></section>
<?php if ($marketing_document !== array()) : ?><section class="kklidi-members-section"><h2><?php esc_html_e('Optional consent', 'kklidi-members'); ?></h2><details><summary><?php echo esc_html(sprintf(__('Marketing communications · Version %s', 'kklidi-members'), $marketing_document['version'])); ?></summary><div class="kklidi-members-document"><?php echo wp_kses_post($marketing_document['content']); ?></div></details><label class="kklidi-members-check" for="kklidi-members-consent-marketing"><input id="kklidi-members-consent-marketing" type="checkbox" name="consent_marketing" value="1"> <?php esc_html_e('I agree to receive marketing information.', 'kklidi-members'); ?></label></section><?php endif; ?>
<button class="kklidi-members-button" type="submit"><?php esc_html_e('Create account', 'kklidi-members'); ?></button>
</form><?php endif; ?>
<nav class="kklidi-members-form-links" aria-label="<?php esc_attr_e('Registration help', 'kklidi-members'); ?>"><a href="<?php echo esc_url($login_url); ?>"><?php esc_html_e('Already have an account? Log in', 'kklidi-members'); ?></a><a href="<?php echo esc_url($home_url); ?>"><?php esc_html_e('Back to site', 'kklidi-members'); ?></a></nav>
</section></main><?php wp_footer(); ?></body></html>
