<?php if (!defined('ABSPATH')) { exit; } ?>
<!doctype html><html <?php language_attributes(); ?>><head>
<meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title><?php esc_html_e('Request withdrawal', 'kklidi-members'); ?></title><?php wp_head(); ?>
</head><body <?php body_class('kklidi-members-page kklidi-members-page--withdrawal'); ?>><?php wp_body_open(); ?>
<main class="kklidi-members-main"><section class="kklidi-members-card" aria-labelledby="kklidi-members-page-title"><header class="kklidi-members-header"><h1 id="kklidi-members-page-title"><?php esc_html_e('Request withdrawal', 'kklidi-members'); ?></h1><p><?php esc_html_e('Submitting this request blocks sign-in immediately. Deletion-eligible data is processed according to the applicable retention period; records required by law or service policy may be retained.', 'kklidi-members'); ?></p></header>
<?php if ($message !== '') : ?><p class="kklidi-members-notice kklidi-members-notice--error" role="alert"><?php echo esc_html($message); ?></p><?php endif; ?>
<?php if (!user_can($user, 'manage_options')) : ?><div class="kklidi-members-danger-zone"><form class="kklidi-members-form" method="post"><input type="hidden" name="kklidi_members_withdrawal" value="1"><input type="hidden" name="request_id" value="<?php echo esc_attr($request_id); ?>"><?php wp_nonce_field('kklidi_members_withdrawal', '_kklidi_members_withdrawal_nonce'); ?><div class="kklidi-members-field"><label for="kklidi-members-withdrawal-password"><?php esc_html_e('Current password', 'kklidi-members'); ?></label><div class="kklidi-members-password-control"><input id="kklidi-members-withdrawal-password" type="password" name="current_password" autocomplete="current-password" required data-kklidi-members-password<?php echo isset($field_errors['current_password']) ? ' aria-invalid="true" aria-describedby="kklidi-members-withdrawal-password-error"' : ''; ?>><button class="kklidi-members-password-toggle" type="button" data-kklidi-members-password-toggle aria-controls="kklidi-members-withdrawal-password" aria-pressed="false" aria-label="<?php esc_attr_e('Show password', 'kklidi-members'); ?>" data-show-label="<?php esc_attr_e('Show password', 'kklidi-members'); ?>" data-hide-label="<?php esc_attr_e('Hide password', 'kklidi-members'); ?>"></button></div><?php if (isset($field_errors['current_password'])) : ?><span class="kklidi-members-field-error" id="kklidi-members-withdrawal-password-error"><?php echo esc_html($field_errors['current_password']); ?></span><?php endif; ?></div><button class="kklidi-members-button kklidi-members-button--danger" type="submit"><?php esc_html_e('Submit request and block sign-in', 'kklidi-members'); ?></button></form></div><?php endif; ?>
<?php $route_links = array(array('url' => kklidi_members_account_url(), 'label' => __('Account', 'kklidi-members')), array('url' => kklidi_members_profile_url(), 'label' => __('Profile', 'kklidi-members')), array('url' => home_url('/'), 'label' => __('Home', 'kklidi-members'))); require KKLIDI_MEMBERS_DIR . 'templates/partials/route-links.php'; ?>
</section></main><?php wp_footer(); ?></body></html>
